name: flutter_survey_js
description: Parse and display survey js
version: 0.0.1-dev.5
homepage: https://github.com/Goxiaoy/flutter_survey_js

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.3.8
  im_stepper: ^1.0.1+1
  flutter_widget_from_html_core: ^0.15.2
  reactive_forms: ^17.0.1
  reactive_date_time_picker: ^4.0.0
  reactive_date_range_picker: ^2.1.0
  reactive_segmented_control: ^2.0.1
  reactive_advanced_switch: ^2.1.0
  reactive_image_picker: ^7.0.0
  implicitly_animated_reorderable_list_2: ^0.6.0
  flutter_colorpicker: ^1.1.0
  signature: ^5.5.0
  logging: ^1.3.0
  json_annotation: ^4.9.0
  platform: ^3.1.6
  file: ^7.0.1
  group_button: ^5.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
  uses-material-design: true

